"""Create receipt product payment models.

Revision ID: ec55c18d426d
Revises: ae95fe21594c
Create Date: 2024-11-19 18:12:17.428808+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ec55c18d426d"
down_revision: str | None = "ae95fe21594c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

payment_type_enum = sa.Enum("CASH", "CASHLESS", name="payment_type")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_receipts_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", payment_type_enum, nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], name=op.f("fk_payments_receipt_id_receipts")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], name=op.f("fk_products_receipt_id_receipts")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    op.drop_table("payments")
    op.drop_table("receipts")
    # ### end Alembic commands ###
    payment_type_enum.drop(op.get_bind())
