name: Code Quality
on: [push]

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Check Lockfile
        run: uv lock --locked

  linting:
    runs-on: ubuntu-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run Linter
        run: just lint

  formatting:
    runs-on: ubuntu-latest
    needs: [lockfile]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Check Formatting
        run: just check-fmt
